ServerEvents.recipes(event => {
    //移除物品：炸弹，靛蓝炸弹
    event.remove({ output: 'supplementaries:bomb' })
    //移除物品：ftb过滤
    event.remove({ mod: 'itemfilters' })
    //移除物品：ftb任务
    event.remove({ mod: 'ftbquests' })
    //移除配方：搅拌合成玫瑰石英
    event.remove({ id: 'create:crafting/materials/rose_quartz' })
    //移除物品：粘液头盔及靴子
    event.remove({ output: Item.of('create_sa:slime_helmet') })
    event.remove({ output: Item.of('create_sa:slime_boots') })
    //移除物品：黄铜无人机相关，黄铜cube
    event.remove({ output: 'create_sa:copper_magnet' })
    event.remove({ output: 'create_sa:brass_cube' })
    event.remove({ output: Item.of('create_sa:drone_controller') })
    event.remove({ output: 'create_sa:fan_component' })
    event.remove({ output: 'create_sa:vault_component' })
    event.remove({ output: 'create_sa:brass_drone_item' })
    //移除物品：钢制机壳
    event.remove({ output: 'alloyed:steel_casing' })
    //移除配方：沉浸式飞机
    event.remove({ id: 'immersive_aircraft:airship' })
    event.remove({ id: 'immersive_aircraft:quadrocopter' })
    event.remove({ id: 'immersive_aircraft:gyrodyne' })
    event.remove({ id: 'immersive_aircraft:biplane' })
    event.remove({ id: 'immersive_aircraft:boiler' })
    event.remove({ id: 'immersive_aircraft:steel_boiler' })
    event.remove({ id: 'immersive_aircraft:engine' })
    event.remove({ id: 'immersive_aircraft:propeller' })
    event.remove({ id: 'immersive_aircraft:industrial_gears' })
    event.remove({ id: 'immersive_aircraft:improved_landing_gear' })
    //移除配方：钢锭
    event.remove({ id: 'alloyed:mixing/steel_ingot' })
    event.remove({ id: 'ad_astra:recipes/steel_ingot_from_blasting_iron_ingot' })
    event.remove({ id: 'ad_astra:recipes/steel_ingot_from_nuggets' })
    event.remove({ id: 'ad_astra:recipes/steel_block' })
    event.remove({ id: 'ad_astra:recipes/steel_ingot' })
    //移除配方：银河系漫游指南
    event.remove({ id: 'ad_astra:recipes/astrodux' })
    //移除配方：打火石
    event.remove({ id: "minecraft:flint_and_steel" })
    event.remove({ id: 'alexsmobs:flint_n_steel_dropbear_claw' })
    //移除配方：锤子
    event.remove({ output: Item.of('ad_astra:hammer') })
    event.remove({ input: Item.of('ad_astra:hammer') })
    //移除配方：ad_astra重叠物品
    event.remove({ output: 'ad_astra:compressor' })
    event.remove({ input: 'ad_astra:compressor' })
    event.remove({ output: 'ad_astra:coal_generator' })
    event.remove({ input: 'ad_astra:coal_generator' })
    event.remove({ output: 'ad_astra:cable_duct' })
    event.remove({ input: 'ad_astra:cable_duct' })
    event.remove({ output: 'ad_astra:ostrum_fluid_pipe' })
    event.remove({ input: 'ad_astra:ostrum_fluid_pipe' })
    event.remove({ output: 'ad_astra:desh_cable' })
    event.remove({ input: 'ad_astra:desh_cable' })
    event.remove({ output: 'ad_astra:steel_cable' })
    event.remove({ input: 'ad_astra:steel_cable' })
    event.remove({ output: 'ad_astra:desh_fluid_pipe' })
    event.remove({ input: 'ad_astra:desh_fluid_pipe' })
    event.remove({ output: 'ad_astra:fluid_pipe_duct' })
    event.remove({ input: 'ad_astra:fluid_pipe_duct' })
    event.remove({ output: 'ad_astra:water_pump' })
    event.remove({ input: 'ad_astra:water_pump' })
    event.remove({ output: 'ad_astra:nasa_workbench' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_1_rocket' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_2_rocket' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_3_rocket' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_4_rocket' })
    event.remove({ output: 'ad_astra:wrench' })
    event.remove({ output: 'alloyedguns:musket' })
    event.remove({ output: 'alloyedguns:flintlock' })
    event.remove({ input: 'alloyedguns:small_iron_pipe' })
    event.remove({ output: 'alloyedguns:small_iron_pipe' })
    event.remove({ output: 'cgm:workbench' })
    event.remove({ input: 'cgm:workbench' })
    event.remove({ input: 'create_enchantment_industry:experience_rotor' })
    event.remove({ output: 'create_enchantment_industry:experience_rotor' })
    event.remove({ id: 'cgm:crude_shot' })
    event.remove({ output: 'alloyedguns:complex_bullet_casing' })
    event.remove({ input: 'alloyedguns:complex_bullet_casing' })
    event.remove({ output: 'extradelight:apple_sauce' })
    event.remove({ output: 'vinery:cherry_boat' })
    event.remove({ input: 'vinery:cherry_boat' })
    event.remove({ input: 'beachparty:palm_boat' })
    event.remove({ output: 'beachparty:palm_boat' })
})
