StartupEvents.registry('item', e => {
    // 粗钢锭
    e.create("createdelight:raw_steel_ingot")
        .maxStackSize(64)
        .translationKey("item.createdelight.raw_steel_ingot")
        .group("create_delight")
        .tag("forge:ingots/raw_steel")
        .rarity("common")
        .tooltip(Text.translate("tooltip.createdelight.raw_steel_ingot"))
    // 锤炼中的粗钢锭
    e.create("createdelight:hammering_raw_steel_ingot")
        .maxStackSize(64)
        .translationKey("item.createdelight.hammering_raw_steel_ingot")
        .group("create_delight")
        .tag("forge:ingots/hammering_raw_steel")
        .rarity("common")
    // 土豆加牛肉
    e.create("createdelight:potato_stew_beef")
        .food(food => {
            food.hunger(7)
                .saturation(0.6)
                .meat()
                .eaten(ctx => {
                    if (!ctx.level.isClientSide())
                        ctx.player.tell(Text.translatable("text.createdelight.eat_potato_stew_beef").red())
                })
        })
        .translationKey("item.createdelight.potato_stew_beef")
        .group("create_delight")
    // 未激活的凋零之眼
    e.create("createdelight:unactivated_wither_eye")
        .maxStackSize(16)
        .translationKey("item.createdelight.unactivated_wither_eye")
        .group("create_delight")
        .rarity("epic")
    e.create("createdelight:dusty_magical_eye")
        .maxDamage(16)
        .translationKey("item.createdelight.dusty_magical_eye")
        .group("create_delight")
        .rarity("rare")
    // **rs中间产物
    e.create("createdelight:incompleted_1k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_1k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_4k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_4k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_16k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_16k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_64k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_64k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_64k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_64k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_256k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_256k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_1024k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_1024k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_4096k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_4096k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_256k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_256k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_1024k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_1024k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_4096k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_4096k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_16384k_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_16384k_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_16384k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_16384k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_65536k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_65536k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_262144k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_262144k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:incompleted_1048576k_fluid_storage_part")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_1048576k_fluid_storage_part")
        .group("create_delight")
        .rarity("common")
    e.create("createdelight:raw_silicon")
        .maxStackSize(64)
        .translationKey("item.createdelight.raw_silicon")
        .group("create_delight")
        .rarity("common")
    // 注册挂面
    e.create("createdelight:vermicelli")
        .maxStackSize(64)
        .translationKey("item.createdelight.vermicelli")
        .group("create_delight")
    // 注册曲奇面团
    e.create("createdelight:persimmon_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.persimmon_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    e.create("createdelight:lemon_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.lemon_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    e.create("createdelight:chorus_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.chorus_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    e.create("createdelight:green_tea_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.green_tea_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    e.create("createdelight:cranberry_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.cranberry_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    e.create("createdelight:bayberry_cookie_dough")
        .tag("forge:cookie_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.bayberry_cookie_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
        })
    // 开酥相关
    e.create("createdelight:oil_dough")
        .maxStackSize(64)
        .translationKey("item.createdelight.oil_dough")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
                .effect("minecraft:nausea", 200, 1, 1.0)
        })
    e.create("createdelight:puff_pastry")
        .maxStackSize(64)
        .translationKey("item.createdelight.puff_pastry")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
                .effect("minecraft:nausea", 200, 1, 1.0)
        })
    e.create("createdelight:yorkshire_pudding_and_beef")
        .maxStackSize(64)
        .translationKey("item.createdelight.yorkshire_pudding_and_beef")
        .group("create_delight")
        .food(food => {
            food.hunger(12)
                .saturation(1)
        })
    e.create("createdelight:oil_dough_with_butter")
        .maxStackSize(64)
        .translationKey("item.createdelight.oil_dough_with_butter")
        .group("create_delight")
        .food(food => {
            food.hunger(1)
                .saturation(1)
                .fastToEat()
                .effect("minecraft:hunger", 200, 1, 1.0)
                .effect("minecraft:nausea", 200, 1, 1.0)
        })
    // 板面
    e.create("createdelight:board_noodles")
        .maxStackSize(64)
        .translationKey("item.createdelight.board_noodles")
        .group("create_delight")
    // 未完成相关
    e.create("createdelight:incomplete_alternator")
        .maxStackSize(64)
        .translationKey("item.createdelight.incomplete_alternator")
    e.create("createdelight:incomplete_diesel_engine")
        .maxStackSize(64)
        .translationKey("item.createdelight.incomplete_diesel_engine")
    e.create("createdelight:incomplete_electric_motor")
        .maxStackSize(64)
        .translationKey("item.createdelight.incomplete_electric_motor")
    e.create("createdelight:incomplete_huge_diesel_engine")
        .maxStackSize(64)
        .translationKey("item.createdelight.incomplete_huge_diesel_engine")
    e.create("createdelight:incomplete_large_diesel_engine")
        .maxStackSize(64)
        .translationKey("item.createdelight.incomplete_large_diesel_engine")
    e.create("createdelight:incompleted_modular_accumulator")
        .maxStackSize(64)
        .translationKey("item.createdelight.incompleted_modular_accumulator")
})